### ISSUE TITLE
Version 3.0.0 published with CRLF line endings

### ISSUE THREAD

**Issue by Baune8D** [zkochan/symlink-dir#14]
symlink-dir is not invokable from command line on macOS if installed with Yarn.
It fails with the following message:
```env: node\r: No such file or directory```

See this issue: https://github.com/yarnpkg/yarn/issues/5480
Apparently npm auto converts line endings to LF which is why it only fails with Yarn.

Reverting to v2.0.1 fixes this issue for now.

Can confirm that using dos2unix on v3.0.0 files also fixes the problem.

**Comment by zkochan** [comment]
maybe I published it from Windows. I'll retry from Linux

**Comment by zkochan** [comment]
:ship: 3.0.1

**Comment by Baune8D** [comment]
Can confirm it seems to be working now. Thanks!
